### ISSUE TITLE
Desktop + Mobile: Make body text size, style, format consistent

### ISSUE THREAD

**Issue by oliviaboldt** [pixelbakery/pixelbakery-website#177]
some body text is bolded, some isn't, some is super small while other body is almost the same size as the H2s

@jordanlambrecht

**Comment by jordanlambrecht** [comment]
@oliviaboldt Please elaborate

**Comment by oliviaboldt** [comment]
@jordanlambrecht body and description text needs to consistently be same style (e.g. bolded, regular, etc.) and size across the site
