### ISSUE TITLE
Work page: Something about this section bothers me lol

### ISSUE THREAD

**Issue by oliviaboldt** [pixelbakery/pixelbakery-website#209]
<img width="1389" alt="Screen Shot 2022-03-16 at 4 13 18 PM (2)" src="https://user-images.githubusercontent.com/94932415/158692133-049a1881-adf6-4354-860b-3eb754e299cf.png">

**Comment by jordanlambrecht** [comment]
@oliviaboldt can we close this out

**Comment by oliviaboldt** [comment]
If ya want @jordanlambrecht – I'm still not happy with it though lol

**Comment by oliviaboldt** [comment]
It's the only section of our website that I'm not happy with
